name: CI-CD-MVC-MonsterASP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup MSBuild
      - uses: microsoft/setup-msbuild@v2

      # Restore NuGet packages using msbuild
      - run: msbuild Portfolio/Portfolio.csproj /t:Restore

# Build and publish
      - shell: pwsh
        run: |
         $publishDir = "$env:GITHUB_WORKSPACE\publish"
         Write-Host "Publishing to $publishDir"
         msbuild Portfolio/Portfolio.csproj `
         /p:Configuration=Release `
         /p:DeployOnBuild=true `
         /p:WebPublishMethod=FileSystem `
         /p:PublishDir=$publishDir

      # Deploy via FTP
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: publish/
          server-dir: ${{ secrets.FTP_PATH }}
